### ISSUE TITLE
Lib folder in org.grits.toolbox.glycanarray.om

### ISSUE THREAD

**Issue by ReneRanzinger** [GritsToolbox/org.grits.toolbox#17]
In [jar.org.grits.toolbox.glycanarray.om](https://github.com/GritsToolbox/jar.org.grits.toolbox.glycanarray.om) is a lib folder. I removed _cfg-lib.xml_ and the sequence files. Are they needed?

**Comment by senaarpinar** [comment]
They are not needed.
