### ISSUE TITLE
What is org.grits.toolbox.feature (SNV)

### ISSUE THREAD

**Issue by ReneRanzinger** [GritsToolbox/org.grits.toolbox#21]
In the SVN there is plugin project - org.grits.toolbox.feature. What is this. Do we need it?

**Comment by senaarpinar** [comment]
this was created while attempting to convert GRITS into a feature-based application. We don't need it.

**Comment by senaarpinar** [comment]
I remember that this was part of the attempt to create a GRITS update site so the developers would get GRITS into their eclipse environment and build on top of that. There is a documentation in the old wiki about this plugin: http://trac.grits-toolbox.org/wiki/GRITSUpdateSite
