### ISSUE TITLE
What is org.grits.toolbox.view.glycantree

### ISSUE THREAD

**Issue by ReneRanzinger** [GritsToolbox/org.grits.toolbox#24]
There is a plugin project in SVN - org.grits.toolbox.view.glycantree. What is this? Do we need it?

**Comment by senaarpinar** [comment]
This is an old plugin which didn't become part of GRITS. It was meant to show relationships among the glycans in a tree view as far as I can remember.

**Comment by ReneRanzinger** [comment]
Archived: https://github.com/GritsToolbox/org.grits.toolbox.view.glycantree
