### ISSUE TITLE
Dependencies for org.grits.toolbox.util.structure.glycan

### ISSUE THREAD

**Issue by ReneRanzinger** [GritsToolbox/org.grits.toolbox#25]
The [org.grits.toolbox.util.structure.glycan](https://github.com/GritsToolbox/org.grits.toolbox.util.structure.glycan) has a lib folder with a jar from [jar.org.grits.toolbox.util.structure.glycan.om](https://github.com/GritsToolbox/jar.org.grits.toolbox.util.structure.glycan.om) in it. This jar should go to [bundle.org.grits.toolbox.lib](https://github.com/GritsToolbox/bundle.org.grits.toolbox.lib) and this plugin be a dependency for org.grits.toolbox.util.structure.glycan.

**Comment by senaarpinar** [comment]
similar to the widgets plugin, [bundle.org.grits.toolbox.lib](https://github.com/GritsToolbox/bundle.org.grits.toolbox.lib) has a dependency to [org.grits.toolbox.util.structure.glycan](https://github.com/GritsToolbox/org.grits.toolbox.util.structure.glycan) and this kind of change will create a cycle in dependencies.
