### ISSUE TITLE
Dependencies for org.grits.toolbox.widgets

### ISSUE THREAD

**Issue by ReneRanzinger** [GritsToolbox/org.grits.toolbox#26]
The [org.grits.toolbox.widgets](https://github.com/GritsToolbox/org.grits.toolbox.widgets) has a lib folder with a jar from [jar.org.grits.toolbox.widgets.om](https://github.com/GritsToolbox/jar.org.grits.toolbox.widgets.om) in it. This jar should go to [bundle.org.grits.toolbox.lib](https://github.com/GritsToolbox/bundle.org.grits.toolbox.lib) and this plugin be a dependency for org.grits.toolbox.widgets.

**Comment by senaarpinar** [comment]
[bundle.org.grits.toolbox.lib](https://github.com/GritsToolbox/bundle.org.grits.toolbox.lib) has a dependency to [org.grits.toolbox.widgets](https://github.com/GritsToolbox/org.grits.toolbox.widgets) already and it would be a cycle if we try to do it that way.
