### ISSUE TITLE
Review org.eclipse.nebula.widgets.nattable (SVN)

### ISSUE THREAD

**Issue by ReneRanzinger** [GritsToolbox/org.grits.toolbox#7]
There was a bundle org.eclipse.nebula.widgets.nattable in SVN. It seems to contain nattable jars but seems unused. Is it needed? If yes, which versions of the jars (there are duplicates).

**Comment by senaarpinar** [comment]
This does not seem to be used. We are using nattable packages directly from eclipse nattable implementation. There is a documentation in trac explaining the upgrade from nattable 0.9 to 1.4  during which we removed the dependency to this plugin.
