### ISSUE TITLE
Review not migrated plugins

### ISSUE THREAD

**Issue by ReneRanzinger** [GritsToolbox/org.grits.toolbox#8]
There are several plugins that seem obsolete or not used. I did not migrate them. Do we need them?
* org.grits.toolbox.lab.maor
* org.grits.toolbox.lab.servicelab
* org.grits.toolbox.simglycan

**Comment by senaarpinar** [comment]
I don't know much about maor and simglycan. Simglycan is an old plugin that seems to handle importing from SimGlycan but it is not used in GRITS.
We already agreed to archive and keep servicelab plugin.
