### ISSUE TITLE
Review bundle org.glycoinfo

### ISSUE THREAD

**Issue by ReneRanzinger** [GritsToolbox/org.grits.toolbox#9]
There are duplicate JARs in [bundle.org.glycoinfo](https://github.com/GritsToolbox/bundle.org.glycoinfo). We should remove the once not needed. Also why is there a plugin.xml in a bundle? There is also a slf4j jar here that should not be there. There is a separate bundle.org.slf4j for it. We should remove it there and make the other bundle a required-bundle in the MANIFEST.

**Comment by senaarpinar** [comment]
slf4j versions are different. The one used in this plugin is newer than the one in slf4j bundle. Not sure if it would cause problems if we use the older version in this plugin. I am not even sure which jar necessitated including slf4j as a dependency here.
I will remove the unused jars.

**Comment by senaarpinar** [comment]
removed unused jars and use slf4j as a plugin dependency. org.glycoinfo is only referenced in glycan builder and I tested the sequence conversions to make sure it is still working.

**Comment by ReneRanzinger** [comment]
Lets also look at the graphical glycan builder.

**Comment by senaarpinar** [comment]
I already quickly tested the drawing part.
